name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Checkout do código fonte
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login no Docker Hub usando secrets
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Build da imagem Docker
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/node-hello-world:${{ github.sha }} .

      # Push da imagem para o Docker Registry
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/node-hello-world:${{ github.sha }}

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      # Checkout do código fonte
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar o `kubectl` usando o secret `KUBECONFIG`
      - name: Setup kubectl
        run: |
          echo "${{ secrets.KUBECONFIG }}" > /tmp/kubeconfig
          export KUBECONFIG=/tmp/kubeconfig

      # Deploy da nova imagem no Kubernetes
      - name: Deploy to Kubernetes
        run: kubectl set image deployment/node-hello-world node-hello-world=${{ secrets.DOCKER_USERNAME }}/node-hello-world:${{ github.sha }}
# teste