name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Passo 1: Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Passo 2: Definir diretório de trabalho
      - name: Change working directory
        run: cd /home/oliheitor/actions-runner/DevOps-Hello-World

      # Passo 3: Login no Docker Hub usando o token
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Passo 4: Build da imagem Docker
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-hello-world:${{ github.sha }} .

      # Passo 5: Push da imagem Docker
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/node-hello-world:${{ github.sha }}
          