name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Passo 1: Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Passo 2: Login no Docker Hub usando o token
      - name: Login to Docker Hub
        shell: bash
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Passo 3: Build da imagem Docker
      - name: Build Docker Image
        shell: bash
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-hello-world:${{ github.sha }} .

      # Passo 4: Push da imagem Docker
      - name: Push Docker Image
        shell: bash
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/node-hello-world:${{ github.sha }}

          